version: 0.2
phases:
   install:
      runtime-versions:
         docker: 18
   pre_build:
      commands:
      - echo "Entered the pre-build phase"
      - $(aws ecr get-login  --no-include-email --region $AWS_REGION)
   build:
      commands:
      - echo "Entered build phase"
      - cd insurance-claim-microservice
      - mvn compile
      - mvn package
      - echo " building docker image"
      - docker build -t service/claimapp .
      - docker tag service/claimapp 408832051344.dkr.ecr.ap-southeast-1.amazonaws.com/pod-13-insurance:claimapp
   post_build:
      commands:
      - echo "Entered the post-build phase"
      - docker push 408832051344.dkr.ecr.ap-southeast-1.amazonaws.com/pod-13-insurance:claimapp
      - printf '[{"name":"claimapp-container","imageUri":"%s"}]' 408832051344.dkr.ecr.ap-southeast-1.amazonaws.com/pod-13-insurance:claimapp>taskdefinition.json
artifacts:
   files:
   - insurance-claim-microservice/taskdefinition.json