version: 0.2
phases:
   install:
      runtime-versions:
         docker: 18
   pre_build:
      commands:
      - echo "Entered the pre-build phase"
      - $(aws ecr get-login  --no-include-email --region $AWS_REGION)
   build:
      commands:
      - echo "Entered build phase"
      - cd ip-treatment-offerings
      - mvn compile
      - mvn package
      - echo " building docker image"
      - docker build -t service/offeringapp .
      - docker tag service/offeringapp 408832051344.dkr.ecr.ap-southeast-1.amazonaws.com/pod-13-offering:offeringapp
   post_build:
      commands:
      - echo "Entered the post-build phase"
      - docker push 408832051344.dkr.ecr.ap-southeast-1.amazonaws.com/pod-13-offering:offeringapp
      - printf '[{"name":"offering-container","imageUri":"%s"}]' 408832051344.dkr.ecr.ap-southeast-1.amazonaws.com/pod-13-offering:offeringapp>taskdefinition.json
artifacts:
   files:
   - ip-treatment-offerings/taskdefinition.json