version: 0.2
phases:
   install:
      runtime-versions:
         docker: 18
   pre_build:
      commands:
      - echo "Entered the pre-build phase"
      - $(aws ecr get-login  --no-include-email --region $AWS_REGION)
   build:
      commands:
      - echo "Entered build phase"
      - cd authorization-service
      - mvn compile
      - mvn package
      - echo " building docker image"
      - docker build -t service/authsapp .
      - docker tag service/authsapp 408832051344.dkr.ecr.ap-southeast-1.amazonaws.com/pod-13-auth:authsapp
   post_build:
      commands:
      - echo "Entered the post-build phase"
      - docker push 408832051344.dkr.ecr.ap-southeast-1.amazonaws.com/pod-13-auth:authsapp
      - printf '[{"name":"authsapp-container","imageUri":"%s"}]' 408832051344.dkr.ecr.ap-southeast-1.amazonaws.com/pod-13-auth:authsapp>taskdefinition.json
artifacts:
   files:
   - authorization-service/taskdefinition.json