insert into  IPTREATMENT_PACKAGE( AILMENT_CATEGORY, COST, TEST_DETAIL,TREATMENT_DURATIONIN_WEEKS,TREATMENT_PACKAGE_NAME  ) Values ( 'Urology', 4000,  'UPT1, UPT2',4, 'Package 1');
insert into  IPTREATMENT_PACKAGE( AILMENT_CATEGORY, COST, TEST_DETAIL,TREATMENT_DURATIONIN_WEEKS,TREATMENT_PACKAGE_NAME  ) Values ( 'Orthopaedics', 2500,  'OPT1, OPT2',4, 'Package 1');
insert into  IPTREATMENT_PACKAGE( AILMENT_CATEGORY, COST, TEST_DETAIL,TREATMENT_DURATIONIN_WEEKS,TREATMENT_PACKAGE_NAME  ) Values ( 'Urology', 5000,  'UPT3, UPT4',6, 'Package 2'); 
insert into  IPTREATMENT_PACKAGE( AILMENT_CATEGORY, COST, TEST_DETAIL,TREATMENT_DURATIONIN_WEEKS,TREATMENT_PACKAGE_NAME  ) Values ( 'Orthopaedics', 3000,  'OPT3, OPT4',6, 'Package 2');
insert into  SPECIALIST_DETAIL(AREA_OF_EXPERTISE, CONTACT_NUMBER, EXPERIENCE_IN_YEAR, NAME) Values ( 'Orthopaedics', '9827369493',4,'Dr. Mahesh Tripathi');
insert into  SPECIALIST_DETAIL(AREA_OF_EXPERTISE, CONTACT_NUMBER, EXPERIENCE_IN_YEAR, NAME) Values ( 'Urology', '8770279493',3,'Dr. Rajesh Kukreja');
insert into  SPECIALIST_DETAIL(AREA_OF_EXPERTISE, CONTACT_NUMBER, EXPERIENCE_IN_YEAR, NAME) Values ( 'Orthopaedics', '9425638482',12,'Dr. A.K. Sarang');
insert into  SPECIALIST_DETAIL(AREA_OF_EXPERTISE, CONTACT_NUMBER, EXPERIENCE_IN_YEAR, NAME) Values ( 'Urology', '7999998182',15,'Dr. Vivek Jha');

